### ISSUE TITLE
看上去不能模拟数据是吗

### ISSUE THREAD

**Issue by kk8686** [Tencent/WeFlow#103]
我没找到模拟假数据的功能，要自己开发加入对吧

**Comment by littledu** [comment]
自己用 mockjs 生成假数据进行调试

**Comment by kk8686** [comment]
我自己构造的是这样的，只是比较理想的预期就是WeFlow能朽好一套机制让开发者直接配置数据格式和地址就能直接用了

**Comment by littledu** [comment]
gulp有个理念就是希望插件只做一件事情，简单而不失专业化，同样，既然有专业的mock库了，就不让这个工具功能过于多，有些开发者也会偏向于自己熟悉的mock工具或库

**Comment by lunaticnotcrazy** [comment]
使用weflow过程中less文件代码错误，不能打开项目，只能定位到是less编译有问题但是不能具体定位到是哪行代码有问题，只能手动排查很浪费时间，有更好的方法排除问题么？

**Comment by kk8686** [comment]
@littledu 
我的意思并不是要重复造轮的意思，可以集成mockjs，提供快速的数据URL和数据定义然后就能得到数据

现在我自己拿mockjs搭个模拟数据服务端还要创建http服务器，当收到请求时比如URL是 /user/list.json的话我还要在这个服务器里写读取逻辑，比如require mock目录下的user/list.json.js，这个js里大概的代码就是

```js
module.exports = require('mockjs').mock({
	message : '',
	code : 0,
	'data|20' : [{
		'disable|0-1' : 1,  //状态
		'id|1-9999': 1,
		name : '@cfirst@cname',
		'mobile|13378494691-19378494691' : 1,
		email : /[a-z0-9]{6,20}@xxxx\.com/,  //邮箱
		permission_group_name : /[\u4E00-\u9FA5]{3}/,  //权限组名称
		last_login : '@DATETIME("2016-MM-dd HH:mm:ss")'     //最后一次登录
	}]
});
```

个人希望构建平台能直接提供mock数据的http服务器（设定URL和端口），预定好mock数据目录，开发者安装构建平台后只要在mock目录下添加对应路径的目录和js文件使用mockjs返回数据就行了

现在每一个创业公司的小团队搞前后分离都要每个团队自己手动搭这样的mock服务器其实是麻烦的工作
