### ISSUE TITLE
在mac下修改dev和dist配置APP无法运行

### ISSUE THREAD

**Issue by NemoPhoenix** [Tencent/WeFlow#109]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` 
- [x] WeFlow 版本： `v1.3.3`

#### 反馈具体描述：

在mac下我修改了dev和dist配置重启APP后APP处于假死状态无法运行

**Comment by hzlzh** [comment]
你改了哪些配合？是定制需要么，可以贴上来看看
