### ISSUE TITLE
开发环境报错

### ISSUE THREAD

**Issue by boboxiao** [Tencent/WeFlow#110]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.12.5)`
- [x] WeFlow 版本： `v1.3.x`
- [x] Node 版本： `v6.0.0`
#### 反馈具体描述：
开发环境报如下错误：
kq_init: detected broken kqueue; not using.: Undefined error: 0

**Comment by littledu** [comment]
可能是系统版本某些模块缺失，暂时无法确定具体问题
