### ISSUE TITLE
中文escape编码在编译之后被重新转成中文

### ISSUE THREAD

**Issue by Pumpe** [Tencent/WeFlow#113]
#### 运行环境

- [x] 操作系统 & 版本： `Windows (10)` 
- [x] WeFlow 版本： `v1.3.3`

#### 反馈具体描述：
由于一些原因，在js脚本中的中文字符需要使用escape编码最后才能使用，避免一些输出时的charset不同导致的中文乱码，但是在使用weflow打包编译的时候，会将escape编码后的代码重新编译为中文

**Comment by littledu** [comment]
请问你是如何使用的？我试了如下：

1. 
```
output = escape('%u4E2D%u6587');
console.log(output);
```

2. 
```
output = escape('中文');
console.log(output);
```

都正常
