### ISSUE TITLE
热刷新谷歌浏览器下无法回到原位置

### ISSUE THREAD

**Issue by songhongkai99** [Tencent/WeFlow#114]
#### 运行环境 

- [x] 操作系统 & 版本：`macOS (10.12.5)` 
- [x] WeFlow 版本： `v1.3.3`

#### 反馈具体描述：
热刷新无法回到原位置, 页面有滚动的情况下 热刷新后回到了页面的顶部而不是原来的位置

**Comment by hzlzh** [comment]
你是说  Livereload 功能吧？[wiki](https://github.com/Tencent/tmt-workflow/wiki/%E2%92%91-LiveReload)
更改源码会自动刷新浏览器中的页面，此时会保留之前的滚动条位置，不会回到顶部的，你再试试？或者有重现的视频可以给我们看下。
