### ISSUE TITLE
生产编译后未生成dist目录

### ISSUE THREAD

**Issue by lilyneaoer** [Tencent/WeFlow#115]
#### 运行环境

- [x] 操作系统 & 版本：`Win10`  
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：生产编译后未生成dist目录

-------------------------------附件：日志----------------------------------
compileLess success.
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:147 compileSass success.
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:159 compileAutoprefixer success.
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:177 miniCSS success.
D:\WeFlow-win32-x64\resources\app\node_modules\weflow-imagemin\index.js:89 gulp-imagemin: Minified 0 images
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:205 imageminSprite success.
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:216 copyMedia success.
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:228 uglifyJs success.
D:\WeFlow-win32-x64\resources\app\node_modules\weflow-imagemin\index.js:89 gulp-imagemin: Minified 49 images (saved 72.34 kB - 11.8%)
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:191 imageminImg success.
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:251 compileHtml success.
D:\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:351 Nothing changed!
app.js:651 dist 编译完成

**Comment by hzlzh** [comment]
运行默认 example 是否正常，比对排查一下

**Comment by lilyneaoer** [comment]
compileLess success.
compileSass success.
compileAutoprefixer success.
miniCSS success.
copyMedia success.
uglifyJs success.
gulp-imagemin: Minified 6 images (saved 11.04 kB - 3.6%)
imageminImg success.
gulp-imagemin: Minified 5 images (saved 42.55 kB - 39.1%)
imageminSprite success.
compileHtml success.
dist 编译完成
//example正常编译完成，开始编译有问题的项目
compileLess success.
compileSass success.
compileAutoprefixer success.
miniCSS success.
gulp-imagemin: Minified 0 images
imageminSprite success.
copyMedia success.
uglifyJs success.
gulp-imagemin: Minified 49 images (saved 72.34 kB - 11.8%)
imageminImg success.
compileHtml success.
Nothing changed!
dist 编译完成
//编译结束，没有生成dist目录
======================================
帮忙看一下日志，到底是哪里出问题了，百思不得其解啊。

**Comment by lilyneaoer** [comment]
compileLess success.
compileSass success.
compileAutoprefixer success.
miniCSS success.
copyMedia success.
uglifyJs success.
gulp-imagemin: Minified 6 images (saved 11.04 kB - 3.6%)
imageminImg success.
gulp-imagemin: Minified 5 images (saved 42.55 kB - 39.1%)
imageminSprite success.
compileHtml success.
dist 编译完成
//example正常编译完成，开始编译有问题的项目
compileLess success.
compileSass success.
compileAutoprefixer success.
miniCSS success.
gulp-imagemin: Minified 0 images
imageminSprite success.
copyMedia success.
uglifyJs success.
gulp-imagemin: Minified 49 images (saved 72.34 kB - 11.8%)
imageminImg success.
compileHtml success.
Nothing changed!
dist 编译完成
//编译结束，没有生成dist目录

帮忙看一下日志，到底是哪里出问题了，百思不得其解啊。

**Comment by lilyneaoer** [comment]
已解决，删除src目录下manifest.json
