### ISSUE TITLE
html中inlinejs 支持没了

### ISSUE THREAD

**Issue by JoveYu** [Tencent/WeFlow#116]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.12.6)`
- [x] WeFlow 版本： `v1.3.3`

#### 反馈具体描述：
之前html里面支持inlinejs的   最近更新了一下  怎么这个功能没有了

**Comment by hzlzh** [comment]
是这个问题么？
https://github.com/Tencent/WeFlow/issues/104

**Comment by JoveYu** [comment]
1.3.2中使用gulp-usemin支持将js编译的时候写入html  如

```html
<!-- build:inlinejs -->
<script src="../lib/angular-min.js"></script>
<script src="../lib/angular-animate-min.js"></script>
<!-- endbuild -->

<!-- build:inlinecss -->
<link rel="stylesheet" href="css/clear.css"/>
<link rel="stylesheet" href="css/main.css"/>
<!-- endbuild -->
```

而1.3.3使用gulp-useref不支持这种写法   很多之前的代码就编译不过了

**Comment by JoveYu** [comment]
根本没人理

**Comment by hzlzh** [comment]
上次更新升级之后，解决了 #104 的问题，也不再支持 `build:inlinejs` 的写法。
如果你的项目需要 inline 的方案，建议看一下这个 https://github.com/jonkemp/gulp-useref/issues/107 里的 `gulp-inline-css`

对于定制性高的项目，我们建议使用基于命令行的工作流 https://github.com/Tencent/tmt-workflow 方便修改和定制。

或者不适用内联方案：
````
<!-- build:js ../js/build.js -->
    <script src="../js/1.js"></script>
    <script src="../js/2.js"></script>
<!-- endbuild -->
````

**Comment by JoveYu** [comment]
Thanks
