### ISSUE TITLE
官网打不开了

### ISSUE THREAD

**Issue by mosaice** [Tencent/WeFlow#117]
#### 关于 Issues 的提交说明
似乎官网失效了，会修复吗？

#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)`

#### 反馈具体描述：
![image](https://user-images.githubusercontent.com/16646893/29597348-9fe2467c-87f4-11e7-98b0-01b5d3a6add2.png)

**Comment by hzlzh** [comment]
正在修复，今天香港主机收到台风影响

**Comment by hzlzh** [comment]
昨天已经迁移了机器，恢复了访问，另外 demo wiki 更新了，欢迎查看
http://weflow.io/demo/html/doc.html
