### ISSUE TITLE
示例版本lib文件和 新建项目lib文件 有差异

### ISSUE THREAD

**Issue by wanglaodi** [Tencent/WeFlow#125]
WeFlow所创建的项目，lib-rem中针对iPhone 5的转化貌似有问题，
```
// 21.33333333 = 320*20/375 (iPhone 5)
@media only screen and (min-width: 320px) {
  html {
    font-size: 19PX !important;
  }
}
```
通过导入示例项目，发现 lib文件与 新项目创建的lib文件内容不同。
导致rem转换在iphone5下有问题
![image](https://user-images.githubusercontent.com/15962789/36956626-5dbebdd4-206a-11e8-8709-fe48f6526376.png)

**Comment by wanglaodi** [comment]
麻烦更新下lib文件版本~

**Comment by littledu** [comment]
好的
