### ISSUE TITLE
字体库无法引入

### ISSUE THREAD

**Issue by 13714273163** [Tencent/WeFlow#127]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`Windows (7）`  
- [x] WeFlow 版本： `v1.3.3`

#### 反馈具体描述：

字体库无法引入

**Comment by littledu** [comment]
字体库可以放在  media 目录

**Comment by 13714273163** [comment]
可以的谢谢。
