### ISSUE TITLE
liveReload开启了，修改了css中的属性，但是并未生成

### ISSUE THREAD

**Issue by aresa7796** [Tencent/WeFlow#128]
- [x] 操作系统 & 版本： `Windows (10)` 
- [x] WeFlow 版本： `v1.3.3`

liveReload开启着，修改了css中的属性，但是并未生成。
![image](https://user-images.githubusercontent.com/5482599/37822374-3a6545fa-2ec1-11e8-8bea-0669fd098da0.png)
![image](https://user-images.githubusercontent.com/5482599/37822416-51a6da26-2ec1-11e8-8cb5-c7b7a3148061.png)
![image](https://user-images.githubusercontent.com/5482599/37822432-5dd4d6ea-2ec1-11e8-940b-159d6b072eb6.png)

**Comment by hzlzh** [comment]
建议尝试一下运行 demo 之后修改源码，如果有语法错误会导致这种情况的发生。

**Comment by aresa7796** [comment]
我找到问题了，这个工具使用less修改样式的话，是会触发liveReload，使用css不触发liveReload
