### ISSUE TITLE
两个移动端疑问

### ISSUE THREAD

**Issue by 13714273163** [Tencent/WeFlow#129]
进行移动端开始时，需要px转rem（使用的是客户端版）。
问题1，现在默认是使用lib-rem320的设计稿相关代码，这已经严重过时啦，640的才是主流。我是用js设置的rem，想转rem时，75px=1rem，这时怎么设置呢。
问题2，icon精灵图时，我们做的时候只需要写好backgroumd-image，过后自动生成宽高和精灵图（太舒服了），但是移动端需要设置background-size，weflow没有自动生成，这时怎么办，不可能编译后对着压缩后的css一个个加吧~

**Comment by littledu** [comment]
1. 目前用的是 Iphone6 的尺寸 `375` 作为基准啊，没有问题。可以修改代码里面 html 根节点的基准值更改任意你想改的。

2. 需要用到 background-size 是二倍以上的图，如果你的 `slice` 目录下有 @2x.png 的图，是会自动生成一张 `ooxx@2x.png` 的精灵图的，代码也会自动生成相应的 `background-size`，如：

![image](https://user-images.githubusercontent.com/1784673/38728714-313869de-3f43-11e8-87f0-b94f84e2939d.png)

**Comment by 13714273163** [comment]
1.目前设计稿主流都是750呀~，另外对于不用媒体查询，而是用js设置rem的项目好像没考虑到噢（简单来说就是要设置75px=1rem怎么做呢）。
2.对于问题2，在750宽度设计稿时，如果用@2x的图，width和height对应生成的数值不对，您懂得哈。
这两个问题归根结底是因为375与750的设计稿吧，当初没考虑到这个问题，毕竟外面大部分项目都是750设计稿的哟(没法传图，重新发了封邮件带图的到您qq邮箱请查收)

**Comment by littledu** [comment]
看来你还是不明白，375 的二倍就是 750，你好好看 example 研究研究吧

**Comment by hzlzh** [comment]
1. rem 和 px 之间的换算公式和比例是可以自己决定的，不一定非要  75px = 1rem，可以通读一下这个篇文 http://www.alloyteam.com/2016/03/mobile-web-adaptation-tool-rem/#prettyPhoto
2. 如果要使用 rem 解决方案，建议放弃 雪碧图 拼合方案，转而用 HTTP 2.0 的特性不在合并图片到一张里。否则会触发 rem 与 雪碧图的 bug，导致计算结果有小数而造成的 Icon 毛边

**Comment by 13714273163** [comment]
px和rem转换公式和比例都是知道的，现在是自己陷入到另外一些问题上了，再琢磨一下，总之多谢两位。

**Comment by hzlzh** [comment]
@13714273163 rem 方案已经很完善了，主要的大坑在于要抛弃雪碧图使用，多亏有 HTTP 2.0 来解救
