### ISSUE TITLE
运行flexbox 编译不下去 去掉就可以了

### ISSUE THREAD

**Issue by wz569775856** [Tencent/WeFlow#130]
#### 运行环境

- [x] 操作系统 & 版本：Windows 7 
- [x] WeFlow 版本： v1.3.2

#### 反馈具体描述：
运用flexbox后 开发能编译  运行生产后编译不下去  一直停留在css编译
![image](https://user-images.githubusercontent.com/7733812/38847433-1e4925c2-4234-11e8-91fa-36700ebf9f9c.png)
![image](https://user-images.githubusercontent.com/7733812/38847449-366124e8-4234-11e8-9185-2dbf7ff21463.png)
![image](https://user-images.githubusercontent.com/7733812/38847452-3c1db18a-4234-11e8-9041-53f016b020e3.png)

**Comment by hzlzh** [comment]
删除这行是不是就好了，看看是不是语法错误阻塞了
