### ISSUE TITLE
文件路径匹配的 ! 不起作用

### ISSUE THREAD

**Issue by dreampasssser** [Tencent/WeFlow#132]
#### 运行环境

-  操作系统 & 版本： `Windows 10`
-  WeFlow 版本： `v1.3.2`

#### 反馈具体描述：
在配置less文件的src编译路径时，需要排除一些目录和文件，然后就有了下面这样的写法：

`less: [path.join(projectPath, './src/css/**/*.less'), path.join(projectPath, '!./src/css/common/**'), path.join(projectPath, './src/css/**/*.css')],`

其中第二项是要排除的目录，但是编译的时候还是会去编译那个目录，不知道怎么回事。

**Comment by littledu** [comment]
写错了，试试：

```
less: [path.join(projectPath, './src/css/**/*.less'), path.join(projectPath, './src/css/**/*.css'),!path.join(projectPath, './src/css/common/**')],
```

**Comment by dreampasssser** [comment]
@littledu 谢谢啦，您的思路是对的，不过path.join(projectPath, './src/css/common/**')这部分好像相当于一个变量，要用拼接字符串的方式连接它和"!"，
可以这样：'!' + path.join(projectPath, './src/css/common/**')，
也可以用es6的字符串模板：`!${path.join(projectPath, './src/css/common/**')}`。
以上两种方式经证实，在我这儿都是可以的。
