### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by 13714273163** [Tencent/WeFlow#133]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`Windows (7)`  
- [x] WeFlow 版本： `v1.3.3`

#### 反馈具体描述：
下载了好几次1.3.3版本，解压后都提示报错，看了下是内容丢失了，就我发生这个事情吗？

**Comment by littledu** [comment]
换个网络好一点的环境试试呢

**Comment by hzlzh** [comment]
![image](https://user-images.githubusercontent.com/1049575/43828152-4534bbbc-9b2e-11e8-9b9d-f7bcec31e2b0.png)
试试首页告诉下载分流
