### ISSUE TITLE
macOS重装weflow之后无法导入项目

### ISSUE THREAD

**Issue by wangxiao95** [Tencent/WeFlow#135]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.13.3)`  
- [x] WeFlow 版本： `v1.3.3`

#### 反馈具体描述：
因为开发编译文件总是多出代码，怀疑缓存文件，重装了软件；重装之后就导入不了项目了，点文件夹weflow无反应

**Comment by littledu** [comment]
菜单栏-窗口-调试模式，看看报什么错。也可以卸载干净后重装一下试试
