### ISSUE TITLE
需要什么运行环境？

### ISSUE THREAD

**Issue by mxl0721** [Tencent/WeFlow#140]
#### 运行环境

- [x] 操作系统 & 版本：7
- [x] WeFlow 版本： `1.3.3`

反馈具体描述：internal/util.js:32 Ftp.raw[mkd](args): Use Ftp.raw('mkd args') instead
在上传时，老是报错，无法上传，是不是我少了什么运行环境

**Comment by hzlzh** [comment]
由于业务调整，本项目不再更新，感谢大家一直以来的支持。
后续需求会合并到 Feflow 项目进行开发迭代，请移步：
https://github.com/Tencent/feflow
