### ISSUE TITLE
官网无法下载

### ISSUE THREAD

**Issue by mrqasim** [Tencent/WeFlow#142]
![image](https://user-images.githubusercontent.com/27856008/71054960-dcb2cf00-218e-11ea-82f0-59288b32dc54.png)
![image](https://user-images.githubusercontent.com/27856008/71054973-e9372780-218e-11ea-8702-414031e27164.png)

**Comment by hzlzh** [comment]
你可以在这里下载：https://github.com/Tencent/WeFlow/releases

由于业务调整，本项目不再更新，感谢大家一直以来的支持。
后续需求会合并到 Feflow 项目进行开发迭代，请移步：
